FROM node:14-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
ENV PUBLIC_URL=.
RUN npm run build

FROM busybox
COPY --from=builder /app/build /var/www/dashboard

VOLUME /var/www/dashboard
CMD ["sleep", "infinity"]
